[package]
name = "wayfinder-wasm"
version = "14.0.0"
authors = ["7H3LaughingMan"]
edition = "2024"

[profile.release]
opt-level = 3
debug = false
strip = "debuginfo"

[lib]
crate-type = ["cdylib"]
path = "wasm/lib.rs"

[dependencies]
bitvec = "1.1.1"
console_error_panic_hook = "0.1.7"
geo = "0.33.1"
itertools = "0.15.0"
js-sys = "0.3.106"
num = "0.4.3"
pathfinding = "4.16.0"
rstar = "0.13.0"
rust_decimal = { version = "1.43.0", default-features = false, features = [
    "macros",
    "std",
] }
tap = "1.0.1"
wasm-bindgen = "0.2.118"
wasm-bindgen-futures = "0.4.68"
web-sys = { version = "0.3.95", features = [
    "console",
    "WebGl2RenderingContext",
    "WebGlFramebuffer",
    "WebGlRenderbuffer",
    "WebGlTexture",
] }
