[package]
name = "wayfinder-wasm"
version = "14.0.0"
authors = ["7H3LaughingMan"]
edition = "2024"

[profile.release]
opt-level = 3
debug = false
strip = "debuginfo"

[lib]
crate-type = ["cdylib"]
path = "wasm/lib.rs"

[target.wasm32-unknown-unknown.dependencies]
getrandom_v2 = { version = "0.2", features = ["js"], package = "getrandom" }
getrandom_v3 = { version = "0.3", features = [
    "wasm_js",
], package = "getrandom" }

[dependencies]
base64 = "0.22.1"
console_error_panic_hook = "0.1.7"
futures = "0.3.32"
geo = "0.32.0"
itertools = "0.14.0"
js-sys = "0.3.95"
knossos = { git = "https://github.com/7H3LaughingMan/knossos", version = "1.2.0" }
num-traits = "0.2.19"
pathfinding = "4.15.0"
rstar = "0.12.2"
rust_decimal = { version = "1.41.0", default-features = false, features = [
    "macros",
    "std",
] }
svg = "0.18.0"
tap = "1.0.1"
wasm-bindgen = "0.2.118"
wasm-bindgen-futures = "0.4.68"
web-sys = { version = "0.3.95", features = [
    "console",
    "WebGl2RenderingContext",
    "WebGlFramebuffer",
    "WebGlRenderbuffer",
    "WebGlTexture",
] }
