name: Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Build Packs
        run: node build.js
        
      - name: Create Module Archive
        run: zip -r module.zip module.json README.md LICENSE scripts/ languages/ packs/ wasm/

      - name: Archive Module
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: module.zip